import React from "react";
import "../Skills/Skills.css";
const Skills = () => {
  return (
    <div className="skills-section">
      <div className="pl-texts">
        <h1 className="pl-header">Stacks I Use</h1>
      </div>
      <div className="my-languages">
        <div>
          <img
            src="https://img.icons8.com/plasticine/100/null/react.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>React</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/redux.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Redux</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/fluency/48/nextjs.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Next.js</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/fluency/48/null/node-js.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Node</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/nolan/64/express-js.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Express</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/mongodb.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>MongoDB</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/fluency/48/null/mysql-logo.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>MySQL</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/postgreesql.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>PostgreSQL</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/000000/javascript--v1.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>JavaScript</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/typescript.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>TypeScript</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/firebase.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Firebase</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/material-ui.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>MaterialUI</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/sass.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>SASS</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/tailwindcss.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Tailwind</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/bootstrap.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Bootstrap</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/figma--v1.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Figma</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/000000/python.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Python</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/github--v1.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>GitHub</h4>
        </div>
        <div>
          <img
            src="https://img.icons8.com/color/48/null/git.png"
            className="a-language-images"
            alt="no_img"
          />
          <h4>Git</h4>
        </div>
      </div>
    </div>
  );
};

export default Skills;
